### ISSUE TITLE
文件拷贝部分的疑问

### ISSUE THREAD

**Issue by kunlan1949** [noword/EXAPUNKS-Localize#1]
很奇怪的是
![image](https://user-images.githubusercontent.com/43037775/76142296-2aace400-60a7-11ea-9e18-97a624022760.png)
这一步的目录究竟是要拷贝哪些文件

**Comment by noword** [comment]
把整个PackedContent目录copy到images下面就可以，然后删除非.tex为后缀的文件（基本上就是删了PackedContent\fonts目录）
