### ISSUE TITLE
为何全是空白呢，是缺少字库么

### ISSUE THREAD

**Issue by kunlan1949** [noword/EXAPUNKS-Localize#14]
![image](https://user-images.githubusercontent.com/43037775/79096384-9f063180-7d8f-11ea-9de3-36adb3ab0034.png)
![image](https://user-images.githubusercontent.com/43037775/79096396-a88f9980-7d8f-11ea-96ba-26e42cd597fa.png)

**Comment by kunlan1949** [comment]
![image](https://user-images.githubusercontent.com/43037775/79096892-f2c54a80-7d90-11ea-9203-d196b9265312.png)
我已经翻译了第一个json文件，但是发现貌似首页的string.csv的内容并没有展现出来，因此估计翻译的文本也无法展示，肯定是我哪一步出了问题

**Comment by noword** [comment]
https://github.com/noword/EXAPUNKS-Localize/releases
请认真阅读压缩包中的安装说明
