### ISSUE TITLE
直方图无法显示

### ISSUE THREAD

**Issue by TestSubject173** [noword/EXAPUNKS-Localize#15]
![EXAPUNKS_2021_07_25_18_59_02_630](https://user-images.githubusercontent.com/26830170/126896743-d269efda-6c6c-42cd-9836-0c1b9cb938a8.jpg)

最新的补丁和游戏版本

**Comment by noword** [comment]
steam 2020.11.14更新了exe，要重新为exe打补丁。
最近比较忙，等有空了再做。

**Comment by noword** [comment]
已更新
